### PR TITLE
Draft: draft of microbench for gnns

### PR DESCRIPTION
**Pull request by puririshi98**
this will need to have torch_geometric requirements installed for it to run.

### CODE REVIEW

**Comment by kevinstephano** [comment]
What does `jittable()` do to the model?  If we run with TorchDynamo do we still need it?

**Comment by puririshi98** [comment]
> What does `jittable()` do to the model? If we run with TorchDynamo do we still need it?

->

> Under the hood, the [jittable()](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.message_passing.MessagePassing.jittable) call applies the following two modifications to the original class:
> 
> It parses and converts the arguments of the internal [propagate()](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.message_passing.MessagePassing.propagate) function into a NamedTuple which can be handled by the TorchScript compiler.
> 
> It replaces any Union arguments of the forward() function (i.e., arguments that may contain different types) with @torch.jit._overload_method annotations. 

[PyG JIT docs](https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html)
I am not sure wether it is needed for Torch Dynamo since i am not aware of the main difference between torch dynamo and torch script in terms of implementation, only that torch dynamo is supposed to handle dynamic shapes.

**Comment by puririshi98** [comment]
[homogenous.txt](https://github.com/kevinstephano/simple_dl_models/files/9088155/homogenous.txt)
[heterogenous.txt](https://github.com/kevinstephano/simple_dl_models/files/9088161/heterogenous.txt)
these are the outputs when running w/ --torchdynamo in the master-py3-devel container w/ the latest pyg installed on top of it
the functorch install works now but the compilation fails. eager works fine

**Review by kevinstephano — APPROVED** [review]
LGTM

**Comment by kevinstephano** [comment]
I am just going to merge this in.

**Pull request merged**
